# Change baseurl before deploy
baseurl = "https://martinliu.cn"
languageCode = "zh-cn"
#paginate = 8
pagination.pagerSize = 8 
title = "Martin Liu's Blog | SRE培训 | SRE认证 | SRE课程"


# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "martinliu"

googleAnalytics = "G-30EQ6H78E5"

# ignoreLogs = ['warning-goldmark-raw-html']