# Change baseurl before deploy
baseurl = "https://martinliu.cn"
languageCode = "zh-cn"
paginate = 8
title = "Martin Liu's Blog | SRE & DevOps | SRE培训 | SRE认证 | SRE考试"

[params]
  keywords = "SRE,SRE培训,SRE认证,SRE考试,SRE课程,SRE标准,SRE培训课程,SRE认证课程,SRE认证考试"
  siteName = "Martin Liu's Blog | SRE & DevOps | SRE培训 | SRE认证 | SRE考试"
  description = "Martin Liu's Blog | SRE & DevOps | SRE培训 | SRE认证 | SRE考试"


# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "martinliu"

googleAnalytics = "UA-749876-6"