# Uncomment this file to enable multilanguage site support

[en]
    languageName = "English"
    languagedirection = "ltr"
    title = "Martin Liu's Blog | SRE Training | SRE Certification | SRE Courses"
    weight = 2
[zh-cn]
    languageName = "中文"
    languagedirection = "ltr"
    title = "Martin Liu's Blog | SRE培训 | SRE认证 | SRE课程"
    weight = 1
