[[main]]
identifier = "china-ready"
name = "Chinaready"
url = "/en/chinaready/"
[main.params]
icon = "china-ready"

[[main]]
identifier = "slides"
name = "Slides"
url = "https://slides.martinliu.cn/"
[main.params]
icon = "slides"
newtab = true
