[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.100.2"
    HUGO_THEME = "repo"

[context.branch-deploy]
    command = "hugo version && hugo --gc  -b ${DEPLOY_PRIME_URL}"

[context.deploy-preview]
    command = "hugo version  && hugo --gc  -b ${DEPLOY_PRIME_URL}"